// Security Bank Foundation - Integrated Education Program Mock Data Repository
// Realistic seed data reflecting SBF's "Build a School, Build a Nation" and educational CSR programs

const SBF_DATA = {
  // 1. School Building Condition Monitoring
  schools: [
    {
      id: "SCH-001",
      name: "Tuguegarao City Science High School",
      region: "Region II (Cagayan Valley)",
      division: "Tuguegarao City",
      type: "Public Secondary",
      studentCount: 1420,
      buildingTurnoverYear: 2018,
      sbfClassrooms: 8,
      conditionStatus: "Critical", // Critical, Needs Repair, Needs Monitoring, Good
      structuralRating: 54, // out of 100
      roofCondition: "Severe typhoon wind uplift, roof sheet tears",
      electricalStatus: "Needs Rewiring / Water damage risk",
      washStatus: "Non-functional (Plumbing cracked)",
      lastInspectionDate: "2026-08-14",
      inspector: "Engr. Marco Valerio, PE",
      urgentNeeds: "Roof replacement, electrical rewiring in 4 classrooms, beam reinforcement",
      photoUrl: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?auto=format&fit=crop&w=600&q=80",
      history: [
        { date: "2026-08-14", note: "Post-Typhoon Carina damage inspection. 3 rooms unroofed.", status: "Critical" },
        { date: "2025-11-20", note: "Annual structural check. Minor roof rust noted.", status: "Needs Monitoring" }
      ]
    },
    {
      id: "SCH-002",
      name: "Tacloban City National High School",
      region: "Region VIII (Eastern Visayas)",
      division: "Tacloban City",
      type: "Public Secondary",
      studentCount: 2350,
      buildingTurnoverYear: 2016,
      sbfClassrooms: 12,
      conditionStatus: "Needs Repair",
      structuralRating: 68,
      roofCondition: "Localized corrosion, gutter blockages",
      electricalStatus: "Operational with partial breaker trip",
      washStatus: "Functional, requires replacement of 3 faucets",
      lastInspectionDate: "2026-07-22",
      inspector: "Engr. Teresa Lim, SBF Inspector",
      urgentNeeds: "Repaint exterior waterproof coat, gutter replacement, replace ceiling boards",
      photoUrl: "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=600&q=80",
      history: [
        { date: "2026-07-22", note: "Termite treatment required on second floor eaves.", status: "Needs Repair" },
        { date: "2025-09-10", note: "Clean bill of structural stability.", status: "Good" }
      ]
    },
    {
      id: "SCH-003",
      name: "Davao City National High School",
      region: "Region XI (Davao Region)",
      division: "Davao City",
      type: "Public Secondary",
      studentCount: 3100,
      buildingTurnoverYear: 2021,
      sbfClassrooms: 10,
      conditionStatus: "Good",
      structuralRating: 94,
      roofCondition: "Excellent, fully sealed and coated",
      electricalStatus: "Fully compliant, LED energy-efficient fittings",
      washStatus: "Fully functional, gender-segregated clean restrooms",
      lastInspectionDate: "2026-06-18",
      inspector: "Engr. Rafael Santos",
      urgentNeeds: "None. Standard preventive maintenance scheduled for Dec 2026.",
      photoUrl: "https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=600&q=80",
      history: [
        { date: "2026-06-18", note: "Annual inspection passed with high rating.", status: "Good" }
      ]
    },
    {
      id: "SCH-004",
      name: "Cebu City Central School",
      region: "Region VII (Central Visayas)",
      division: "Cebu City",
      type: "Public Elementary",
      studentCount: 1890,
      buildingTurnoverYear: 2019,
      sbfClassrooms: 6,
      conditionStatus: "Needs Monitoring",
      structuralRating: 78,
      roofCondition: "Minor hairline cracks on sealants",
      electricalStatus: "Pass, switchboard label refresh needed",
      washStatus: "Functional, low water pressure on 2nd floor",
      lastInspectionDate: "2026-05-30",
      inspector: "Arch. Angela Ramos",
      urgentNeeds: "Pressure booster check for 2nd-floor washrooms; perimeter window latch fixes",
      photoUrl: "https://images.unsplash.com/photo-1544717302-de2939b7ef71?auto=format&fit=crop&w=600&q=80",
      history: [
        { date: "2026-05-30", note: "Monitor water pump efficiency and crack monitoring.", status: "Needs Monitoring" }
      ]
    },
    {
      id: "SCH-005",
      name: "San Fernando Elementary School",
      region: "Region III (Central Luzon)",
      division: "Pampanga",
      type: "Public Elementary",
      studentCount: 1250,
      buildingTurnoverYear: 2017,
      sbfClassrooms: 8,
      conditionStatus: "Critical",
      structuralRating: 48,
      roofCondition: "Severe flash flood silt intrusion, foundation subsidence check required",
      electricalStatus: "Hazard - Submerged ground outlets isolated",
      washStatus: "Contaminated septic line post-monsoon flood",
      lastInspectionDate: "2026-09-02",
      inspector: "Engr. Marco Valerio, PE",
      urgentNeeds: "Immediate electrical rehabilitation, septic desludging, structural column testing",
      photoUrl: "https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=600&q=80",
      history: [
        { date: "2026-09-02", note: "Habagat flooding affected ground floor. Classrooms evacuated.", status: "Critical" }
      ]
    },
    {
      id: "SCH-006",
      name: "Iloilo National High School",
      region: "Region VI (Western Visayas)",
      division: "Iloilo City",
      type: "Public Secondary",
      studentCount: 2800,
      buildingTurnoverYear: 2022,
      sbfClassrooms: 12,
      conditionStatus: "Good",
      structuralRating: 96,
      roofCondition: "Pristine, insulated double-lock seam roofing",
      electricalStatus: "Complete with solar-ready distribution board",
      washStatus: "High-grade sanitary fixtures in perfect condition",
      lastInspectionDate: "2026-07-15",
      inspector: "Engr. Jonathan Reyes",
      urgentNeeds: "Routine landscaping and pathway clearance only.",
      photoUrl: "https://images.unsplash.com/photo-1588072432836-e10032774350?auto=format&fit=crop&w=600&q=80",
      history: [
        { date: "2026-07-15", note: "Model building status maintained.", status: "Good" }
      ]
    },
    {
      id: "SCH-007",
      name: "Pasay City West High School",
      region: "National Capital Region (NCR)",
      division: "Pasay City",
      type: "Public Secondary",
      studentCount: 2100,
      buildingTurnoverYear: 2015,
      sbfClassrooms: 8,
      conditionStatus: "Needs Repair",
      structuralRating: 64,
      roofCondition: "Aging corrugated sheets, minor leaks during monsoon",
      electricalStatus: "Aging wiring requires circuit breaker upgrade",
      washStatus: "Functional, drainage drain tile clearing needed",
      lastInspectionDate: "2026-08-01",
      inspector: "Engr. Teresa Lim, SBF Inspector",
      urgentNeeds: "Roof thermal insulation coating, breaker panel renewal",
      photoUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=600&q=80",
      history: [
        { date: "2026-08-01", note: "Water leakage noted over Room 302 and Room 303.", status: "Needs Repair" }
      ]
    },
    {
      id: "SCH-008",
      name: "Baguio City National High School",
      region: "Cordillera Administrative Region (CAR)",
      division: "Baguio City",
      type: "Public Secondary",
      studentCount: 1980,
      buildingTurnoverYear: 2020,
      sbfClassrooms: 10,
      conditionStatus: "Needs Monitoring",
      structuralRating: 82,
      roofCondition: "Slope drainage requires periodic pine needle clearing",
      electricalStatus: "Standard compliant",
      washStatus: "Functional, hot water line in science lab checked",
      lastInspectionDate: "2026-06-10",
      inspector: "Arch. Angela Ramos",
      urgentNeeds: "Eaves cleaning and moisture seal around mountainous side facade",
      photoUrl: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=600&q=80",
      history: [
        { date: "2026-06-10", note: "Mild humidity condensation on northern wall.", status: "Needs Monitoring" }
      ]
    }
  ],

  // 2. Teacher Competency & Training Monitoring
  teachers: [
    {
      id: "TCH-101",
      name: "Maria Consolacion Santos",
      school: "Tuguegarao City Science High School",
      subject: "Science & Biology",
      gradeLevel: "Grade 9-10",
      trainingProgram: "SBF-Ateneo STEM Inquiry & Critical Thinking",
      trainingBatch: "Batch 12 (2025)",
      preTestScore: 54,
      postTestScore: 92,
      gainPercent: 70.4,
      competencyStatus: "Improved", // Improved, Maintained, Minimal Improvement, Requires Follow-up Training
      pedagogyScore: 95,
      subjectMasteryScore: 90,
      digitalLiteracyScore: 88,
      cascaded: true,
      lastEvaluated: "2026-06-15",
      notes: "Exceptional mastery demonstration. Mentoring junior teachers in laboratory experimentation."
    },
    {
      id: "TCH-102",
      name: "Rodelio Mendoza",
      school: "Tacloban City National High School",
      subject: "Mathematics & Statistics",
      gradeLevel: "Grade 8",
      trainingProgram: "SBF-DLSU Math Problem Solving Pedagogy",
      trainingBatch: "Batch 11 (2024)",
      preTestScore: 62,
      postTestScore: 88,
      gainPercent: 41.9,
      competencyStatus: "Improved",
      pedagogyScore: 86,
      subjectMasteryScore: 89,
      digitalLiteracyScore: 82,
      cascaded: true,
      lastEvaluated: "2026-05-10",
      notes: "Integrated interactive GeoGebra toolsets in daily lesson modules."
    },
    {
      id: "TCH-103",
      name: "Clarissa Dela Cruz",
      school: "San Fernando Elementary School",
      subject: "Early Literacy & Reading",
      gradeLevel: "Grade 2-3",
      trainingProgram: "Foundational Literacy & Phonics Mastery",
      trainingBatch: "Batch 14 (2025)",
      preTestScore: 48,
      postTestScore: 52,
      gainPercent: 8.3,
      competencyStatus: "Requires Follow-up Training",
      pedagogyScore: 56,
      subjectMasteryScore: 60,
      digitalLiteracyScore: 50,
      cascaded: false,
      lastEvaluated: "2026-07-20",
      notes: "Requires dedicated coaching on structured literacy intervention and phonemic scaffolding."
    },
    {
      id: "TCH-104",
      name: "Bienvenido Alcantara",
      school: "Pasay City West High School",
      subject: "English & Communication",
      gradeLevel: "Grade 7",
      trainingProgram: "Digital English Language Teaching Strategies",
      trainingBatch: "Batch 13 (2025)",
      preTestScore: 70,
      postTestScore: 76,
      gainPercent: 8.6,
      competencyStatus: "Minimal Improvement",
      pedagogyScore: 72,
      subjectMasteryScore: 78,
      digitalLiteracyScore: 68,
      cascaded: false,
      lastEvaluated: "2026-08-11",
      notes: "Good foundational knowledge; needs practice utilizing blended learning digital tools."
    },
    {
      id: "TCH-105",
      name: "Kristine Joy Bautista",
      school: "Davao City National High School",
      subject: "Physics & General Science",
      gradeLevel: "Grade 11-12 (SHS)",
      trainingProgram: "SBF-Ateneo STEM Inquiry & Critical Thinking",
      trainingBatch: "Batch 12 (2025)",
      preTestScore: 82,
      postTestScore: 85,
      gainPercent: 3.7,
      competencyStatus: "Maintained",
      pedagogyScore: 92,
      subjectMasteryScore: 94,
      digitalLiteracyScore: 90,
      cascaded: true,
      lastEvaluated: "2026-06-30",
      notes: "Consistently top-tier performer; serves as Division Lead Facilitator."
    },
    {
      id: "TCH-106",
      name: "Eduardo Fernandez",
      school: "Cebu City Central School",
      subject: "Elementary Mathematics",
      gradeLevel: "Grade 5-6",
      trainingProgram: "SBF-DLSU Math Problem Solving Pedagogy",
      trainingBatch: "Batch 14 (2025)",
      preTestScore: 51,
      postTestScore: 89,
      gainPercent: 74.5,
      competencyStatus: "Improved",
      pedagogyScore: 88,
      subjectMasteryScore: 91,
      digitalLiteracyScore: 84,
      cascaded: true,
      lastEvaluated: "2026-07-04",
      notes: "Highest gain in Central Visayas cohort. Cascaded training across 3 clustered elementary schools."
    },
    {
      id: "TCH-107",
      name: "Lourdes Villanueva",
      school: "Iloilo National High School",
      subject: "Chemistry",
      gradeLevel: "Grade 10",
      trainingProgram: "SBF-Ateneo STEM Inquiry & Critical Thinking",
      trainingBatch: "Batch 13 (2025)",
      preTestScore: 74,
      postTestScore: 94,
      gainPercent: 27.0,
      competencyStatus: "Improved",
      pedagogyScore: 94,
      subjectMasteryScore: 96,
      digitalLiteracyScore: 92,
      cascaded: true,
      lastEvaluated: "2026-08-05",
      notes: "Developed open-source chemistry micro-lab experiment kits for public schools."
    },
    {
      id: "TCH-108",
      name: "Arnel Macaraig",
      school: "Baguio City National High School",
      subject: "Information & Communications Tech",
      gradeLevel: "Grade 9-10",
      trainingProgram: "Digital Learning & AI-Assisted Pedagogy",
      trainingBatch: "Batch 15 (2026)",
      preTestScore: 78,
      postTestScore: 80,
      gainPercent: 2.6,
      competencyStatus: "Maintained",
      pedagogyScore: 85,
      subjectMasteryScore: 88,
      digitalLiteracyScore: 96,
      cascaded: false,
      lastEvaluated: "2026-05-18",
      notes: "Strong technical skills; cascade session scheduled for October 2026."
    }
  ],

  // 3. Disaster Damage Reporting
  disasterReports: [
    {
      id: "DIS-2026-001",
      incidentName: "Typhoon Carina (Gaemi)",
      schoolId: "SCH-001",
      schoolName: "Tuguegarao City Science High School",
      incidentDate: "2026-07-24",
      damageType: "Wind & Heavy Rain Damage",
      affectedFacility: "SBF 2-Storey 8-Classroom Building",
      severity: "Critical", // Minor, Moderate, Major, Critical
      estimatedRepairCostPHP: 750000,
      repairStatus: "Approved for Funding", // Reported, Under Assessment, Approved for Funding, Under Repair, Restored
      contractor: "R.C. Cagayan Builders & Infra",
      targetCompletionDate: "2026-11-15",
      photoEvidence: "https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=600&q=80",
      description: "Severe gale-force winds tore 140 sqm of corrugated roofing sheets. Water intrusion damaged ceiling panels and computer peripherals in Room 204."
    },
    {
      id: "DIS-2026-002",
      incidentName: "Southwest Monsoon (Habagat) Flash Floods",
      schoolId: "SCH-005",
      schoolName: "San Fernando Elementary School",
      incidentDate: "2026-08-04",
      damageType: "Flooding & Mud Silt Inundation",
      affectedFacility: "Ground Floor Classrooms (4 units)",
      severity: "Major",
      estimatedRepairCostPHP: 420000,
      repairStatus: "Under Repair",
      contractor: "Pampanga Metro Works",
      targetCompletionDate: "2026-10-20",
      photoEvidence: "https://images.unsplash.com/photo-1544717302-de2939b7ef71?auto=format&fit=crop&w=600&q=80",
      description: "Muddy water reached 1.2m depth. Flooring submerged, door frames warped, electrical junction boxes water-damaged."
    },
    {
      id: "DIS-2026-003",
      incidentName: "Magnitude 6.2 Northern Samar Offshore Earthquake",
      schoolId: "SCH-002",
      schoolName: "Tacloban City National High School",
      incidentDate: "2026-06-12",
      damageType: "Seismic Shaking",
      affectedFacility: "Exterior Parapet & Eaves",
      severity: "Moderate",
      estimatedRepairCostPHP: 180000,
      repairStatus: "Under Assessment",
      contractor: "Pending Bidding",
      targetCompletionDate: "2026-12-01",
      photoEvidence: "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=600&q=80",
      description: "Superficial masonry cracking on perimeter plastering and slight hairline fracture at column-beam joints. Structural load core verified stable."
    },
    {
      id: "DIS-2026-004",
      incidentName: "Localized Severe Thunderstorm Gale",
      schoolId: "SCH-007",
      schoolName: "Pasay City West High School",
      incidentDate: "2026-08-19",
      damageType: "Fallen Tree Branch on Roof Eave",
      affectedFacility: "Stairwell canopy and eave flashing",
      severity: "Minor",
      estimatedRepairCostPHP: 45000,
      repairStatus: "Restored",
      contractor: "Pasay City School Maintenance Taskforce",
      targetCompletionDate: "2026-08-28",
      photoEvidence: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?auto=format&fit=crop&w=600&q=80",
      description: "Acacia branch dislodged 3 galvanized sheets. Gutter replaced and sheets re-anchored. Building cleared for normal class use."
    }
  ],

  // 4. Teacher Learning Cascade Tracking
  cascadeActivities: [
    {
      id: "CAS-301",
      leadTeacherId: "TCH-101",
      leadTeacherName: "Maria Consolacion Santos",
      school: "Tuguegarao City Science High School",
      trainingProgram: "SBF-Ateneo STEM Inquiry & Critical Thinking",
      cascadeActivityTitle: "School-Based Learning Action Cell (LAC): Hands-on STEM Experimentation",
      dateConducted: "2026-07-10",
      durationHours: 16,
      recipientTeacherCount: 22,
      recipientStudentImpact: 840,
      topicsShared: "5E Instructional Model, Low-cost Laboratory Kits, Inquiry Scaffolding",
      feedbackRating: 4.9, // out of 5.0
      documentationStatus: "Verified with Attendance Sheet & Photos",
      division: "Tuguegarao City"
    },
    {
      id: "CAS-302",
      leadTeacherId: "TCH-102",
      leadTeacherName: "Rodelio Mendoza",
      school: "Tacloban City National High School",
      trainingProgram: "SBF-DLSU Math Problem Solving Pedagogy",
      cascadeActivityTitle: "Division LAC Session: Heuristic Problem Solving in Junior High Math",
      dateConducted: "2026-06-25",
      durationHours: 12,
      recipientTeacherCount: 35,
      recipientStudentImpact: 1450,
      topicsShared: "Polya's 4-step framework, Singapore Math Bar Modeling, Assessment Rubrics",
      feedbackRating: 4.8,
      documentationStatus: "Verified with DepEd Division Certificate",
      division: "Tacloban City"
    },
    {
      id: "CAS-303",
      leadTeacherId: "TCH-106",
      leadTeacherName: "Eduardo Fernandez",
      school: "Cebu City Central School",
      trainingProgram: "SBF-DLSU Math Problem Solving Pedagogy",
      cascadeActivityTitle: "District Math Mentorship Workshop (Central Cluster)",
      dateConducted: "2026-07-28",
      durationHours: 20,
      recipientTeacherCount: 48,
      recipientStudentImpact: 1920,
      topicsShared: "Concrete-Pictorial-Abstract (CPA) method for Grades 4-6",
      feedbackRating: 4.95,
      documentationStatus: "Verified with Video Log & Sign-in Forms",
      division: "Cebu City"
    },
    {
      id: "CAS-304",
      leadTeacherId: "TCH-107",
      leadTeacherName: "Lourdes Villanueva",
      school: "Iloilo National High School",
      trainingProgram: "SBF-Ateneo STEM Inquiry & Critical Thinking",
      cascadeActivityTitle: "Western Visayas Science Educators Peer Mentoring",
      dateConducted: "2026-08-15",
      durationHours: 14,
      recipientTeacherCount: 28,
      recipientStudentImpact: 1100,
      topicsShared: "Green Chemistry principles and Microscale Experiments",
      feedbackRating: 4.85,
      documentationStatus: "Verified with Course Syllabus & Evaluations",
      division: "Iloilo City"
    },
    {
      id: "CAS-305",
      leadTeacherId: "TCH-105",
      leadTeacherName: "Kristine Joy Bautista",
      school: "Davao City National High School",
      trainingProgram: "SBF-Ateneo STEM Inquiry & Critical Thinking",
      cascadeActivityTitle: "Davao Regional Physics Demonstration Echo Seminar",
      dateConducted: "2026-07-18",
      durationHours: 16,
      recipientTeacherCount: 42,
      recipientStudentImpact: 1680,
      topicsShared: "Conceptual Physics demonstrations utilizing everyday materials",
      feedbackRating: 4.9,
      documentationStatus: "Verified with Activity Report",
      division: "Davao City"
    }
  ],

  // 5. Scholar Tracer System
  scholars: [
    {
      id: "SCHOLAR-2022-045",
      name: "Alyssa Marie Dizon",
      graduationYear: 2024,
      batchYear: 2020,
      university: "Ateneo de Manila University",
      degree: "BS Computer Science",
      employmentStatus: "Employed", // Employed, Seeking Employment, Further Studies, Unemployed, Information Not Updated
      employer: "Security Bank Corporation - Head Office",
      industry: "Banking & Financial Services",
      position: "Associate Cloud Solutions Architect",
      monthlySalaryBand: "PHP 55,000 - 70,000",
      degreeAlignment: "Directly Aligned",
      lastUpdateDate: "2026-08-10",
      contactEmail: "a.dizon@securitybank.com.ph",
      honors: "Magna Cum Laude",
      notes: "Fast-tracked into Security Bank's IT Leadership Development Program."
    },
    {
      id: "SCHOLAR-2021-018",
      name: "Joshua Kyle Tan",
      graduationYear: 2023,
      batchYear: 2019,
      university: "University of the Philippines Diliman",
      degree: "BS Civil Engineering",
      employmentStatus: "Employed",
      employer: "Megawide Construction Corp",
      industry: "Construction & Infrastructure",
      position: "Project Site Structural Engineer",
      monthlySalaryBand: "PHP 45,000 - 55,000",
      degreeAlignment: "Directly Aligned",
      lastUpdateDate: "2026-07-14",
      contactEmail: "joshua.tan@alumni.up.edu.ph",
      honors: "Cum Laude, Top 10 Civil Engineering Licensure",
      notes: "Volunteering as technical advisor for SBF school construction reviews."
    },
    {
      id: "SCHOLAR-2023-082",
      name: "Bea Patricia Navarro",
      graduationYear: 2025,
      batchYear: 2021,
      university: "Philippine Normal University",
      degree: "Bachelor of Secondary Education (English)",
      employmentStatus: "Employed",
      employer: "DepEd Division of Manila (Araullo High School)",
      industry: "Public Basic Education",
      position: "Teacher I - Junior High School",
      monthlySalaryBand: "PHP 28,000 - 32,000",
      degreeAlignment: "Directly Aligned",
      lastUpdateDate: "2026-06-20",
      contactEmail: "bea.navarro@deped.gov.ph",
      honors: "Summa Cum Laude",
      notes: "Recipient of SBF Excellence in Education Leadership Award."
    },
    {
      id: "SCHOLAR-2023-094",
      name: "Mark Anthony Legaspi",
      graduationYear: 2025,
      batchYear: 2021,
      university: "De La Salle University",
      degree: "BS Accountancy",
      employmentStatus: "Employed",
      employer: "SGV & Co. (Ernst & Young)",
      industry: "Auditing & Advisory",
      position: "Audit Associate",
      monthlySalaryBand: "PHP 35,000 - 45,000",
      degreeAlignment: "Directly Aligned",
      lastUpdateDate: "2026-05-15",
      contactEmail: "mark.legaspi@ph.ey.com",
      honors: "CPA Board Exam Passer",
      notes: "Actively contributing to SBF Alumni Mentorship Network."
    },
    {
      id: "SCHOLAR-2024-110",
      name: "Camille Joy Soriano",
      graduationYear: 2026,
      batchYear: 2022,
      university: "University of Santo Tomas",
      degree: "BS Medical Technology",
      employmentStatus: "Further Studies",
      employer: "UST Faculty of Medicine and Surgery",
      industry: "Medicine / Higher Education",
      position: "Medical Student (Doctor of Medicine)",
      monthlySalaryBand: "Scholarship Stipend",
      degreeAlignment: "Directly Aligned",
      lastUpdateDate: "2026-08-01",
      contactEmail: "c.soriano@med.ust.edu.ph",
      honors: "Magna Cum Laude",
      notes: "Granted full medical school postgraduate scholarship."
    },
    {
      id: "SCHOLAR-2024-122",
      name: "Christian Dale Perez",
      graduationYear: 2026,
      batchYear: 2022,
      university: "Polytechnic University of the Philippines",
      degree: "BS Information Technology",
      employmentStatus: "Seeking Employment",
      employer: "Actively Interviewing (Fintech/Software)",
      industry: "Technology",
      position: "Candidate - Junior Full Stack Developer",
      monthlySalaryBand: "N/A",
      degreeAlignment: "Seeking Aligned",
      lastUpdateDate: "2026-08-25",
      contactEmail: "dale.perez@gmail.com",
      honors: "Best Capstone Project Award",
      notes: "Attending SBF Career Readiness and Interview Prep workshops."
    },
    {
      id: "SCHOLAR-2022-031",
      name: "Janine Rodriguez",
      graduationYear: 2023,
      batchYear: 2019,
      university: "Far Eastern University",
      degree: "BS Business Administration - Marketing",
      employmentStatus: "Information Not Updated",
      employer: "Unknown (Pending Response)",
      industry: "Unknown",
      position: "Unknown",
      monthlySalaryBand: "Unknown",
      degreeAlignment: "Unknown",
      lastUpdateDate: "2025-04-10", // overdue > 12 months!
      contactEmail: "j.rodriguez99@yahoo.com",
      honors: "Dean's Lister",
      notes: "Follow-up email sent on 2026-08-10. SMS reminder queued."
    },
    {
      id: "SCHOLAR-2022-039",
      name: "Gabriel Santos",
      graduationYear: 2024,
      batchYear: 2020,
      university: "Mapua University",
      degree: "BS Mechanical Engineering",
      employmentStatus: "Employed",
      employer: "San Miguel Corporation",
      industry: "Manufacturing & Heavy Industry",
      position: "Plant Reliability Engineer",
      monthlySalaryBand: "PHP 42,000 - 50,000",
      degreeAlignment: "Directly Aligned",
      lastUpdateDate: "2026-07-19",
      contactEmail: "gabriel.santos@mapua.edu.ph",
      honors: "Licensed Mechanical Engineer",
      notes: "Stationed in Bataan manufacturing facility."
    },
    {
      id: "SCHOLAR-2021-009",
      name: "Rochelle Anne Gomez",
      graduationYear: 2023,
      batchYear: 2019,
      university: "University of San Carlos",
      degree: "BS Applied Mathematics",
      employmentStatus: "Information Not Updated",
      employer: "Pending Update",
      industry: "Unknown",
      position: "Unknown",
      monthlySalaryBand: "Unknown",
      degreeAlignment: "Unknown",
      lastUpdateDate: "2025-03-22", // overdue > 12 months!
      contactEmail: "ragomez.usc@gmail.com",
      honors: "Cum Laude",
      notes: "Record flagged for urgent tracer outreach."
    }
  ],

  // 8. Notifications & Alerts Center
  notifications: [
    {
      id: "NOTIF-01",
      type: "disaster",
      severity: "high",
      title: "Urgent Disaster Assessment Required",
      message: "Tuguegarao City Science High School reported unroofed classrooms post-Typhoon Carina. Structural engineer clearance needed.",
      timestamp: "2 hours ago",
      targetModule: "disaster",
      targetId: "DIS-2026-001",
      read: false
    },
    {
      id: "NOTIF-02",
      type: "school",
      severity: "high",
      title: "Critical Facility Submersion Alert",
      message: "San Fernando Elementary School ground floor submerged in habagat flood. Electrical isolation in progress.",
      timestamp: "5 hours ago",
      targetModule: "schools",
      targetId: "SCH-005",
      read: false
    },
    {
      id: "NOTIF-03",
      type: "teacher",
      severity: "medium",
      title: "6-Month Post-Training Reassessment Scheduled",
      message: "Foundational Literacy Batch 14 teachers are due for classroom competency reassessments.",
      timestamp: "1 day ago",
      targetModule: "teachers",
      targetId: "TCH-103",
      read: false
    },
    {
      id: "NOTIF-04",
      type: "cascade",
      severity: "medium",
      title: "Uncascaded Training Reminder",
      message: "2 master teachers from Batch 13 have not yet submitted their school LAC cascade documentation.",
      timestamp: "2 days ago",
      targetModule: "cascade",
      targetId: "CAS-301",
      read: true
    },
    {
      id: "NOTIF-05",
      type: "scholar",
      severity: "low",
      title: "Scholar Tracer Records Stale (>12 Months)",
      message: "2 scholar records (Janine Rodriguez, Rochelle Anne Gomez) have not been updated for over a year.",
      timestamp: "3 days ago",
      targetModule: "scholars",
      targetId: "SCHOLAR-2022-031",
      read: true
    }
  ],

  // 9. User Roles & Access
  users: [
    {
      id: "USR-001",
      name: "Atty. Melissa Aquino",
      role: "Administrator",
      email: "m.aquino@securitybank.com.ph",
      department: "SBF Executive Office",
      status: "Active",
      permissions: "Full Read/Write, System Config, User Management, Approvals"
    },
    {
      id: "USR-002",
      name: "Carlos Dela Paz",
      role: "Foundation Staff",
      email: "c.delapaz@securitybank.com.ph",
      department: "Education Programs Division",
      status: "Active",
      permissions: "Review & Approve Damage Reports, Schedule Inspections, Export Reports"
    },
    {
      id: "USR-003",
      name: "Dr. Evelyn Hernandez",
      role: "School Principal",
      email: "evelyn.hernandez@deped.gov.ph",
      department: "Tuguegarao City Science High School",
      status: "Active",
      permissions: "Submit Facility Incident, View School Building Reports, Confirm Inspection"
    },
    {
      id: "USR-004",
      name: "Maria Consolacion Santos",
      role: "Teacher / Master Trainer",
      email: "consolacion.santos@deped.gov.ph",
      department: "DepEd Region II",
      status: "Active",
      permissions: "Log Pre/Post Tests, Log Cascade Sessions, Upload Attendance Sheets"
    },
    {
      id: "USR-005",
      name: "Alyssa Marie Dizon",
      role: "Scholar",
      email: "a.dizon@securitybank.com.ph",
      department: "SBF Scholar Alumni Chapter NCR",
      status: "Active",
      permissions: "Update Personal Profile, Submit Employment Status, View Alumni Directory"
    }
  ],

  // 10. Data Repository Documents
  documents: [
    {
      id: "DOC-801",
      title: "SBF Standard Classroom Building Structural Specifications (2024 Rev)",
      category: "Architectural & Engineering",
      fileType: "PDF",
      fileSize: "14.2 MB",
      dateAdded: "2024-03-15",
      schoolOrProgram: "All SBF School Buildings",
      uploader: "Engr. Marco Valerio, PE"
    },
    {
      id: "DOC-802",
      title: "Memorandum of Agreement - Security Bank Foundation & DepEd National",
      category: "Legal & Partnerships",
      fileType: "PDF",
      fileSize: "3.8 MB",
      dateAdded: "2023-01-20",
      schoolOrProgram: "Build a School, Build a Nation",
      uploader: "Atty. Melissa Aquino"
    },
    {
      id: "DOC-803",
      title: "Teacher Training Framework & Evaluation Rubrics - SBF-Ateneo Partnership",
      category: "Pedagogy & Training",
      fileType: "PDF",
      fileSize: "8.5 MB",
      dateAdded: "2025-02-11",
      schoolOrProgram: "Teacher Training Program",
      uploader: "Carlos Dela Paz"
    },
    {
      id: "DOC-804",
      title: "Standard Post-Disaster Rapid Damage Assessment Form (RADAR Template)",
      category: "Disaster Risk & Assessment",
      fileType: "XLSX",
      fileSize: "1.2 MB",
      dateAdded: "2025-06-30",
      schoolOrProgram: "Disaster Damage Response",
      uploader: "Engr. Teresa Lim"
    },
    {
      id: "DOC-805",
      title: "SBF College Scholarship Guidelines & Annual Tracer Compliance Policy",
      category: "Scholarship Operations",
      fileType: "PDF",
      fileSize: "2.4 MB",
      dateAdded: "2024-08-01",
      schoolOrProgram: "College Scholarship Program",
      uploader: "Carlos Dela Paz"
    }
  ]
};
